### PR TITLE
Add a bunch of endpoints and clean up code

### PR DESCRIPTION
**Pull request by mircodezorzi**
The following function (and corresponding features) were added:

- `noticeboard`: retrieve noticeboard information
- `download_notice`: download noticeboard item
- `documents`: retrieve documents information
- `download_document`: download document
- `didactics`: retrieve didactics information
- `dowload_didacticis_item`: download didactic item
- `download_didactics`: download all didactic items (declared in tools.py)

Other minor changes include:

- Code clean up

### CODE REVIEW

**Comment by MarcoBuster** [comment]
Thank you very much for your PR! As soon I have some time, I'll approve your code and merge it.

**Comment by MarcoBuster** [comment]
Please check the [Travis build](https://travis-ci.org/MarcoBuster/ClasseVivaAPI/jobs/650105581?utm_source=github_status), is failing.

**Comment by mircodezorzi** [comment]
Looks like I forgot to ignore some errors in pycodestyle. I'll fix this as soon as I can.

**Comment by MarcoBuster** [comment]
Sure. No rush, take your time, it's fine :)

**Comment by mircodezorzi** [comment]
I left E203, E221, E272, and E501 as blacklisted as I find that alignment of imports and dictionaries makes the code a lot more cleaner and easier to read.

**Pull request merged**
